git:
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
promptToReturnFromSubprocess: false
os:
  edit: "lazygit-edit {{filename}}"
  editAtLine: "lazygit-edit {{filename}} {{line}}"
  editInTerminal: false
customCommands:
  - key: 'Q'
    description: 'Send diff hunks to Nvim QF'
    context: 'global'
    command: 'lazygit-to-qf'
    loadingText: 'Dumping to QF...'
