#!/usr/bin/env bash
if [[ -n "$ZELLIJ_SESSION_NAME" ]]; then
    id="$ZELLIJ_SESSION_NAME"
elif [[ -n "$TMUX" ]]; then
    id="$(tmux display-message -p '#{session_name}-#{window_name}' | tr -dc 'a-zA-Z0-9_-')"
else
    id="default"
fi
exec command nvim --listen "/tmp/nvim-${id}.sock" "$@"
