#!/usr/bin/env bash
if [[ -n "$ZELLIJ_SESSION_NAME" ]]; then
    id="$ZELLIJ_SESSION_NAME"
elif [[ -n "$TMUX" ]]; then
    id="$(tmux display-message -p '#{session_name}-#{window_name}' | tr -dc 'a-zA-Z0-9_-')"
else
    id="default"
fi
sock="/tmp/nvim-${id}.sock"
if [[ -S "$sock" ]] && ! command nvim --server "$sock" --remote-expr 'v:servername' &>/dev/null; then
    rm -f "$sock"
fi
if [[ -n "$TMUX" ]]; then
    win_name="$(tmux display-message -p '#{window_name}')"
    if [[ "$win_name" == [[:ascii:]]* ]]; then
        tmux rename-window nvim
        command nvim --listen "$sock" "$@"
        tmux set-option -w automatic-rename on
    else
        exec command nvim --listen "$sock" "$@"
    fi
else
    exec command nvim --listen "$sock" "$@"
fi
