-- -Flattened from vague.nvim. Vendor-owned.
vim.cmd('highlight clear')
if vim.fn.has('syntax_on') == 1 then vim.cmd('syntax reset') end
vim.g.colors_name = 'vague'

local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = '#aeaed1' })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@boolean", { fg = '#e0a363', bold = true })
hi(0, "@character", { fg = '#e8b589', italic = true })
hi(0, "@character.special", { fg = '#6e94b2' })
hi(0, "@comment", { link = "Comment" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@constant", { fg = '#aeaed1' })
hi(0, "@constant.builtin", { fg = '#e0a363', bold = true })
hi(0, "@constructor", { fg = '#aeaed1' })
hi(0, "@constructor.lua", { fg = '#9bb4bc' })
hi(0, "@diff.delta", { bg = '#41362a' })
hi(0, "@diff.minus", { bg = '#3b242a' })
hi(0, "@diff.plus", { bg = '#293125' })
hi(0, "@function", { fg = '#c48282' })
hi(0, "@function.builtin", { fg = '#c48282' })
hi(0, "@function.call", { fg = '#bb9dbd' })
hi(0, "@function.macro", { fg = '#aeaed1' })
hi(0, "@function.method.call", { fg = '#9bb4bc' })
hi(0, "@keyword", { fg = '#6e94b2' })
hi(0, "@keyword.conditional", { fg = '#6e94b2' })
hi(0, "@keyword.exception", { fg = '#6e94b2' })
hi(0, "@keyword.import", { fg = '#aeaed1' })
hi(0, "@keyword.operator", { fg = '#6e94b2' })
hi(0, "@keyword.return", { fg = '#6e94b2', italic = true })
hi(0, "@label", { fg = '#6e94b2' })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.builtinConstant", { fg = '#e0a363', bold = true })
hi(0, "@lsp.type.builtinType", { fg = '#b4d4cf', bold = true })
hi(0, "@lsp.type.class", { fg = '#aeaed1' })
hi(0, "@lsp.type.comment", { fg = '#606079', italic = true })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { fg = '#aeaed1' })
hi(0, "@lsp.type.enumMember", { fg = '#b4d4cf' })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { fg = '#bb9dbd' })
hi(0, "@lsp.type.generic", { fg = '#9bb4bc' })
hi(0, "@lsp.type.interface", { fg = '#aeaed1' })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { fg = '#aeaed1' })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { fg = '#aeaed1' })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { fg = '#bb9dbd' })
hi(0, "@lsp.type.property", { fg = '#9bb4bc' })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfParameter", { fg = '#b4d4cf' })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { fg = '#aeaed1' })
hi(0, "@lsp.type.variable", { fg = '#aeaed1' })
hi(0, "@lsp.typemod.function.builtin", { fg = '#c48282' })
hi(0, "@lsp.typemod.function.defaultLibrary", { fg = '#c48282' })
hi(0, "@lsp.typemod.function.definition", { fg = '#c48282' })
hi(0, "@lsp.typemod.variable.defaultLibrary", { fg = '#e0a363', bold = true })
hi(0, "@lsp.typemod.variable.definition", { fg = '#c3c3d5' })
hi(0, "@markup", { fg = '#cdcdcd' })
hi(0, "@markup.heading", { fg = '#6e94b2', bold = true })
hi(0, "@markup.heading.1.delimiter.vimdoc", { fg = '#141415', bg = '#141415', sp = '#cdcdcd', nocombine = true })
hi(0, "@markup.heading.2.delimiter.vimdoc", { fg = '#141415', bg = '#141415', sp = '#cdcdcd', underline = true, nocombine = true })
hi(0, "@markup.italic", { fg = '#cdcdcd', italic = true })
hi(0, "@markup.link", { fg = '#e8b589' })
hi(0, "@markup.link.uri", { fg = '#e8b589', underline = true })
hi(0, "@markup.list", { fg = '#c48282' })
hi(0, "@markup.math", { fg = '#e8b589' })
hi(0, "@markup.quote.markdown", { fg = '#606079' })
hi(0, "@markup.raw", { fg = '#aeaed1' })
hi(0, "@markup.strikethrough", { fg = '#606079', strikethrough = true })
hi(0, "@markup.strong", { fg = '#cdcdcd', bold = true })
hi(0, "@markup.underline", { fg = '#cdcdcd', underline = true })
hi(0, "@module", { fg = '#aeaed1' })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@number", { fg = '#e0a363' })
hi(0, "@number.float", { fg = '#e0a363' })
hi(0, "@operator", { fg = '#90a0b5' })
hi(0, "@property", { fg = '#c3c3d5' })
hi(0, "@punctuation", { link = "Delimiter" })
hi(0, "@punctuation.special", { fg = '#6e94b2' })
hi(0, "@string", { fg = '#e8b589', italic = true })
hi(0, "@string.escape", { fg = '#6e94b2' })
hi(0, "@string.regexp", { fg = '#6e94b2' })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.symbol", { fg = '#aeaed1' })
hi(0, "@string.special.url", { fg = '#c48282' })
hi(0, "@tag", { link = "Tag" })
hi(0, "@tag.attribute", { fg = '#aeaed1' })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = '#cdcdcd' })
hi(0, "@text.diff.add", { bg = '#293125' })
hi(0, "@text.diff.delete", { bg = '#3b242a' })
hi(0, "@type", { fg = '#9bb4bc' })
hi(0, "@type.builtin", { fg = '#b4d4cf', bold = true })
hi(0, "@type.declaration", { fg = '#aeaed1' })
hi(0, "@type.definition", { fg = '#aeaed1' })
hi(0, "@variable", { fg = '#cdcdcd' })
hi(0, "@variable.builtin", { fg = '#b4d4cf' })
hi(0, "@variable.member", { fg = '#b4d4cf' })
hi(0, "@variable.parameter", { fg = '#bb9dbd' })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { fg = '#7fa563' })
hi(0, "Annotation", { fg = '#7e98e8', bg = '#1e2030', italic = true })
hi(0, "Boolean", { fg = '#e0a363', bold = true })
hi(0, "Changed", { fg = '#f3be7c' })
hi(0, "Character", { fg = '#e8b589' })
hi(0, "ColorColumn", { bg = '#252530' })
hi(0, "Comment", { fg = '#606079', italic = true })
hi(0, "ComplHint", { link = "NonText" })
hi(0, "ComplHintMore", { link = "MoreMsg" })
hi(0, "Conceal", { fg = '#c48282' })
hi(0, "Conditional", { fg = '#6e94b2' })
hi(0, "Constant", { fg = '#aeaed1' })
hi(0, "CurSearch", { fg = '#cdcdcd', bg = '#405065' })
hi(0, "Cursor", { fg = '#141415', bg = '#cdcdcd' })
hi(0, "CursorColumn", { bg = '#252530' })
hi(0, "CursorIM", { link = "Cursor" })
hi(0, "CursorLine", { bg = '#252530' })
hi(0, "CursorLineFold", { link = "FoldColumn" })
hi(0, "CursorLineNr", { fg = '#cdcdcd' })
hi(0, "CursorLineSign", { link = "SignColumn" })
hi(0, "Debug", { fg = '#aeaed1' })
hi(0, "Define", { fg = '#606079' })
hi(0, "Delimiter", { fg = '#cdcdcd' })
hi(0, "DiagnosticDeprecated", { sp = '#ffc0b9', strikethrough = true })
hi(0, "DiagnosticError", { fg = '#d8647e', bold = true })
hi(0, "DiagnosticFloatingError", { link = "DiagnosticError" })
hi(0, "DiagnosticFloatingHint", { link = "DiagnosticHint" })
hi(0, "DiagnosticFloatingInfo", { link = "DiagnosticInfo" })
hi(0, "DiagnosticFloatingOk", { link = "DiagnosticOk" })
hi(0, "DiagnosticFloatingWarn", { link = "DiagnosticWarn" })
hi(0, "DiagnosticHint", { fg = '#7e98e8' })
hi(0, "DiagnosticInfo", { fg = '#aeaed1', italic = true })
hi(0, "DiagnosticOk", { fg = '#7fa563' })
hi(0, "DiagnosticSignError", { link = "DiagnosticError" })
hi(0, "DiagnosticSignHint", { link = "DiagnosticHint" })
hi(0, "DiagnosticSignInfo", { link = "DiagnosticInfo" })
hi(0, "DiagnosticSignOk", { link = "DiagnosticOk" })
hi(0, "DiagnosticSignWarn", { link = "DiagnosticWarn" })
hi(0, "DiagnosticUnderlineError", { sp = '#d8647e', undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = '#7e98e8', undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = '#aeaed1', undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = '#7fa563', undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = '#f3be7c', undercurl = true })
hi(0, "DiagnosticUnnecessary", { link = "Comment" })
hi(0, "DiagnosticVirtualLinesError", { link = "DiagnosticError" })
hi(0, "DiagnosticVirtualLinesHint", { link = "DiagnosticHint" })
hi(0, "DiagnosticVirtualLinesInfo", { link = "DiagnosticInfo" })
hi(0, "DiagnosticVirtualLinesOk", { link = "DiagnosticOk" })
hi(0, "DiagnosticVirtualLinesWarn", { link = "DiagnosticWarn" })
hi(0, "DiagnosticVirtualTextError", { fg = '#d8647e', bold = true })
hi(0, "DiagnosticVirtualTextHint", { fg = '#7e98e8' })
hi(0, "DiagnosticVirtualTextInfo", { fg = '#aeaed1', italic = true })
hi(0, "DiagnosticVirtualTextOk", { fg = '#7fa563' })
hi(0, "DiagnosticVirtualTextWarn", { fg = '#f3be7c', bold = true })
hi(0, "DiagnosticWarn", { fg = '#f3be7c', bold = true })
hi(0, "DiffAdd", { bg = '#293125' })
hi(0, "DiffChange", { bg = '#41362a' })
hi(0, "DiffDelete", { bg = '#3b242a' })
hi(0, "DiffFile", { fg = '#6e94b2' })
hi(0, "DiffIndexLine", { fg = '#606079' })
hi(0, "DiffText", { bg = '#6d583e' })
hi(0, "DiffTextAdd", { link = "DiffText" })
hi(0, "Directory", { fg = '#7e98e8' })
hi(0, "EndOfBuffer", { fg = '#606079' })
hi(0, "Error", { bg = '#d8647e', bold = true })
hi(0, "ErrorMsg", { fg = '#d8647e', bold = true })
hi(0, "Exception", { fg = '#6e94b2' })
hi(0, "ExtraWhitespace", { fg = '#cdcdcd', bg = '#d8647e' })
hi(0, "Float", { fg = '#e0a363' })
hi(0, "FloatBorder", { fg = '#878787' })
hi(0, "FloatFooter", { link = "FloatTitle" })
hi(0, "FloatShadow", { bg = '#333738' })
hi(0, "FloatShadowThrough", { bg = '#333738' })
hi(0, "FloatTitle", { fg = '#878787' })
hi(0, "FoldColumn", { fg = '#606079' })
hi(0, "Folded", { fg = '#606079', bg = '#252530' })
hi(0, "Function", { fg = '#c48282' })
hi(0, "Identifier", { fg = '#aeaed1' })
hi(0, "Ignore", { link = "Normal" })
hi(0, "IncSearch", { fg = '#141415', bg = '#405065' })
hi(0, "Include", { fg = '#6e94b2' })
hi(0, "Keyword", { fg = '#6e94b2' })
hi(0, "Label", { fg = '#6e94b2' })
hi(0, "LineNr", { fg = '#606079' })
hi(0, "LineNrAbove", { link = "LineNr" })
hi(0, "LineNrBelow", { link = "LineNr" })
hi(0, "LspCodeLens", { fg = '#606079', italic = true })
hi(0, "LspCodeLensSeparator", { fg = '#606079' })
hi(0, "LspCxxHlSkippedRegion", { fg = '#606079' })
hi(0, "LspCxxHlSkippedRegionBeginEnd", { fg = '#90a0b5' })
hi(0, "LspInlayHint", { link = "NonText" })
hi(0, "LspReferenceRead", { bg = '#606079' })
hi(0, "LspReferenceTarget", { link = "LspReferenceText" })
hi(0, "LspReferenceText", { bg = '#606079' })
hi(0, "LspReferenceWrite", { bg = '#606079' })
hi(0, "LspSignatureActiveParameter", { link = "Visual" })
hi(0, "Macro", { fg = '#aeaed1' })
hi(0, "MatchParen", { fg = '#cdcdcd', bg = '#333738' })
hi(0, "ModeMsg", { fg = '#e8b589' })
hi(0, "ModesVisual", { bg = '#e0a363' })
hi(0, "MoreMsg", { fg = '#c48282', bold = true })
hi(0, "MsgSeparator", { fg = '#e8b589', bg = '#252530', bold = true })
hi(0, "NonText", { fg = '#606079' })
hi(0, "Normal", { fg = '#cdcdcd', bg = '#141415' })
hi(0, "NormalFloat", { fg = '#cdcdcd', bg = '#141415' })
hi(0, "Number", { fg = '#e0a363' })
hi(0, "NvimAnd", { link = "NvimBinaryOperator" })
hi(0, "NvimArrow", { link = "Delimiter" })
hi(0, "NvimAssignment", { link = "Operator" })
hi(0, "NvimAssignmentWithAddition", { link = "NvimAugmentedAssignment" })
hi(0, "NvimAssignmentWithConcatenation", { link = "NvimAugmentedAssignment" })
hi(0, "NvimAssignmentWithSubtraction", { link = "NvimAugmentedAssignment" })
hi(0, "NvimAugmentedAssignment", { link = "NvimAssignment" })
hi(0, "NvimBinaryMinus", { link = "NvimBinaryOperator" })
hi(0, "NvimBinaryOperator", { link = "NvimOperator" })
hi(0, "NvimBinaryPlus", { link = "NvimBinaryOperator" })
hi(0, "NvimCallingParenthesis", { link = "NvimParenthesis" })
hi(0, "NvimColon", { link = "Delimiter" })
hi(0, "NvimComma", { link = "Delimiter" })
hi(0, "NvimComparison", { link = "NvimBinaryOperator" })
hi(0, "NvimComparisonModifier", { link = "NvimComparison" })
hi(0, "NvimConcat", { link = "NvimBinaryOperator" })
hi(0, "NvimConcatOrSubscript", { link = "NvimConcat" })
hi(0, "NvimContainer", { link = "NvimParenthesis" })
hi(0, "NvimCurly", { link = "NvimSubscript" })
hi(0, "NvimDict", { link = "NvimContainer" })
hi(0, "NvimDivision", { link = "NvimBinaryOperator" })
hi(0, "NvimDoubleQuote", { link = "NvimStringQuote" })
hi(0, "NvimDoubleQuotedBody", { link = "NvimStringBody" })
hi(0, "NvimDoubleQuotedEscape", { link = "NvimStringSpecial" })
hi(0, "NvimDoubleQuotedUnknownEscape", { link = "NvimInvalidValue" })
hi(0, "NvimEnvironmentName", { link = "NvimIdentifier" })
hi(0, "NvimEnvironmentSigil", { link = "NvimOptionSigil" })
hi(0, "NvimFigureBrace", { link = "NvimInternalError" })
hi(0, "NvimFloat", { link = "NvimNumber" })
hi(0, "NvimIdentifier", { link = "Identifier" })
hi(0, "NvimIdentifierKey", { link = "NvimIdentifier" })
hi(0, "NvimIdentifierName", { link = "NvimIdentifier" })
hi(0, "NvimIdentifierScope", { link = "NvimIdentifier" })
hi(0, "NvimIdentifierScopeDelimiter", { link = "NvimIdentifier" })
hi(0, "NvimInternalError", { fg = '#ff0000', bg = '#ff0000' })
hi(0, "NvimInvalid", { link = "Error" })
hi(0, "NvimInvalidAnd", { link = "NvimInvalidBinaryOperator" })
hi(0, "NvimInvalidArrow", { link = "NvimInvalidDelimiter" })
hi(0, "NvimInvalidAssignment", { link = "NvimInvalid" })
hi(0, "NvimInvalidAssignmentWithAddition", { link = "NvimInvalidAugmentedAssignment" })
hi(0, "NvimInvalidAssignmentWithConcatenation", { link = "NvimInvalidAugmentedAssignment" })
hi(0, "NvimInvalidAssignmentWithSubtraction", { link = "NvimInvalidAugmentedAssignment" })
hi(0, "NvimInvalidAugmentedAssignment", { link = "NvimInvalidAssignment" })
hi(0, "NvimInvalidBinaryMinus", { link = "NvimInvalidBinaryOperator" })
hi(0, "NvimInvalidBinaryOperator", { link = "NvimInvalidOperator" })
hi(0, "NvimInvalidBinaryPlus", { link = "NvimInvalidBinaryOperator" })
hi(0, "NvimInvalidCallingParenthesis", { link = "NvimInvalidParenthesis" })
hi(0, "NvimInvalidColon", { link = "NvimInvalidDelimiter" })
hi(0, "NvimInvalidComma", { link = "NvimInvalidDelimiter" })
hi(0, "NvimInvalidComparison", { link = "NvimInvalidBinaryOperator" })
hi(0, "NvimInvalidComparisonModifier", { link = "NvimInvalidComparison" })
hi(0, "NvimInvalidConcat", { link = "NvimInvalidBinaryOperator" })
hi(0, "NvimInvalidConcatOrSubscript", { link = "NvimInvalidConcat" })
hi(0, "NvimInvalidContainer", { link = "NvimInvalidParenthesis" })
hi(0, "NvimInvalidCurly", { link = "NvimInvalidSubscript" })
hi(0, "NvimInvalidDelimiter", { link = "NvimInvalid" })
hi(0, "NvimInvalidDict", { link = "NvimInvalidContainer" })
hi(0, "NvimInvalidDivision", { link = "NvimInvalidBinaryOperator" })
hi(0, "NvimInvalidDoubleQuote", { link = "NvimInvalidStringQuote" })
hi(0, "NvimInvalidDoubleQuotedBody", { link = "NvimInvalidStringBody" })
hi(0, "NvimInvalidDoubleQuotedEscape", { link = "NvimInvalidStringSpecial" })
hi(0, "NvimInvalidDoubleQuotedUnknownEscape", { link = "NvimInvalidValue" })
hi(0, "NvimInvalidEnvironmentName", { link = "NvimInvalidIdentifier" })
hi(0, "NvimInvalidEnvironmentSigil", { link = "NvimInvalidOptionSigil" })
hi(0, "NvimInvalidFigureBrace", { link = "NvimInvalidDelimiter" })
hi(0, "NvimInvalidFloat", { link = "NvimInvalidNumber" })
hi(0, "NvimInvalidIdentifier", { link = "NvimInvalidValue" })
hi(0, "NvimInvalidIdentifierKey", { link = "NvimInvalidIdentifier" })
hi(0, "NvimInvalidIdentifierName", { link = "NvimInvalidIdentifier" })
hi(0, "NvimInvalidIdentifierScope", { link = "NvimInvalidIdentifier" })
hi(0, "NvimInvalidIdentifierScopeDelimiter", { link = "NvimInvalidIdentifier" })
hi(0, "NvimInvalidLambda", { link = "NvimInvalidParenthesis" })
hi(0, "NvimInvalidList", { link = "NvimInvalidContainer" })
hi(0, "NvimInvalidMod", { link = "NvimInvalidBinaryOperator" })
hi(0, "NvimInvalidMultiplication", { link = "NvimInvalidBinaryOperator" })
hi(0, "NvimInvalidNestingParenthesis", { link = "NvimInvalidParenthesis" })
hi(0, "NvimInvalidNot", { link = "NvimInvalidUnaryOperator" })
hi(0, "NvimInvalidNumber", { link = "NvimInvalidValue" })
hi(0, "NvimInvalidNumberPrefix", { link = "NvimInvalidNumber" })
hi(0, "NvimInvalidOperator", { link = "NvimInvalid" })
hi(0, "NvimInvalidOptionName", { link = "NvimInvalidIdentifier" })
hi(0, "NvimInvalidOptionScope", { link = "NvimInvalidIdentifierScope" })
hi(0, "NvimInvalidOptionScopeDelimiter", { link = "NvimInvalidIdentifierScopeDelimiter" })
hi(0, "NvimInvalidOptionSigil", { link = "NvimInvalidIdentifier" })
hi(0, "NvimInvalidOr", { link = "NvimInvalidBinaryOperator" })
hi(0, "NvimInvalidParenthesis", { link = "NvimInvalidDelimiter" })
hi(0, "NvimInvalidPlainAssignment", { link = "NvimInvalidAssignment" })
hi(0, "NvimInvalidRegister", { link = "NvimInvalidValue" })
hi(0, "NvimInvalidSingleQuote", { link = "NvimInvalidStringQuote" })
hi(0, "NvimInvalidSingleQuotedBody", { link = "NvimInvalidStringBody" })
hi(0, "NvimInvalidSingleQuotedQuote", { link = "NvimInvalidStringSpecial" })
hi(0, "NvimInvalidSingleQuotedUnknownEscape", { link = "NvimInternalError" })
hi(0, "NvimInvalidSpacing", { link = "ErrorMsg" })
hi(0, "NvimInvalidString", { link = "NvimInvalidValue" })
hi(0, "NvimInvalidStringBody", { link = "NvimStringBody" })
hi(0, "NvimInvalidStringQuote", { link = "NvimInvalidString" })
hi(0, "NvimInvalidStringSpecial", { link = "NvimStringSpecial" })
hi(0, "NvimInvalidSubscript", { link = "NvimInvalidParenthesis" })
hi(0, "NvimInvalidSubscriptBracket", { link = "NvimInvalidSubscript" })
hi(0, "NvimInvalidSubscriptColon", { link = "NvimInvalidSubscript" })
hi(0, "NvimInvalidTernary", { link = "NvimInvalidOperator" })
hi(0, "NvimInvalidTernaryColon", { link = "NvimInvalidTernary" })
hi(0, "NvimInvalidUnaryMinus", { link = "NvimInvalidUnaryOperator" })
hi(0, "NvimInvalidUnaryOperator", { link = "NvimInvalidOperator" })
hi(0, "NvimInvalidUnaryPlus", { link = "NvimInvalidUnaryOperator" })
hi(0, "NvimInvalidValue", { link = "NvimInvalid" })
hi(0, "NvimLambda", { link = "NvimParenthesis" })
hi(0, "NvimList", { link = "NvimContainer" })
hi(0, "NvimMod", { link = "NvimBinaryOperator" })
hi(0, "NvimMultiplication", { link = "NvimBinaryOperator" })
hi(0, "NvimNestingParenthesis", { link = "NvimParenthesis" })
hi(0, "NvimNot", { link = "NvimUnaryOperator" })
hi(0, "NvimNumber", { link = "Number" })
hi(0, "NvimNumberPrefix", { link = "Type" })
hi(0, "NvimOperator", { link = "Operator" })
hi(0, "NvimOptionName", { link = "NvimIdentifier" })
hi(0, "NvimOptionScope", { link = "NvimIdentifierScope" })
hi(0, "NvimOptionScopeDelimiter", { link = "NvimIdentifierScopeDelimiter" })
hi(0, "NvimOptionSigil", { link = "Type" })
hi(0, "NvimOr", { link = "NvimBinaryOperator" })
hi(0, "NvimParenthesis", { link = "Delimiter" })
hi(0, "NvimPlainAssignment", { link = "NvimAssignment" })
hi(0, "NvimRegister", { link = "SpecialChar" })
hi(0, "NvimSingleQuote", { link = "NvimStringQuote" })
hi(0, "NvimSingleQuotedBody", { link = "NvimStringBody" })
hi(0, "NvimSingleQuotedQuote", { link = "NvimStringSpecial" })
hi(0, "NvimSingleQuotedUnknownEscape", { link = "NvimInternalError" })
hi(0, "NvimSpacing", { link = "Normal" })
hi(0, "NvimString", { link = "String" })
hi(0, "NvimStringBody", { link = "NvimString" })
hi(0, "NvimStringQuote", { link = "NvimString" })
hi(0, "NvimStringSpecial", { link = "SpecialChar" })
hi(0, "NvimSubscript", { link = "NvimParenthesis" })
hi(0, "NvimSubscriptBracket", { link = "NvimSubscript" })
hi(0, "NvimSubscriptColon", { link = "NvimSubscript" })
hi(0, "NvimTernary", { link = "NvimOperator" })
hi(0, "NvimTernaryColon", { link = "NvimTernary" })
hi(0, "NvimUnaryMinus", { link = "NvimUnaryOperator" })
hi(0, "NvimUnaryOperator", { link = "NvimOperator" })
hi(0, "NvimUnaryPlus", { link = "NvimUnaryOperator" })
hi(0, "OkMsg", { fg = '#7fa563' })
hi(0, "Operator", { fg = '#90a0b5' })
hi(0, "Pmenu", { fg = '#cdcdcd' })
hi(0, "PmenuBorder", { fg = '#878787' })
hi(0, "PmenuExtra", { link = "Pmenu" })
hi(0, "PmenuExtraSel", { link = "PmenuSel" })
hi(0, "PmenuKind", { link = "Pmenu" })
hi(0, "PmenuKindSel", { link = "PmenuSel" })
hi(0, "PmenuMatch", { bold = true })
hi(0, "PmenuMatchSel", { bold = true })
hi(0, "PmenuSbar", { link = "Pmenu" })
hi(0, "PmenuSel", { fg = '#aeaed1', bg = '#252530' })
hi(0, "PmenuShadow", { link = "FloatShadow" })
hi(0, "PmenuShadowThrough", { link = "FloatShadowThrough" })
hi(0, "PmenuThumb", { bg = '#606079' })
hi(0, "PreCondit", { fg = '#606079' })
hi(0, "PreInsert", { link = "Added" })
hi(0, "PreProc", { fg = '#aeaed1' })
hi(0, "Question", { fg = '#aeaed1' })
hi(0, "QuickFixLine", { bg = '#1c1c24' })
hi(0, "RedrawDebugClear", { bg = '#6b5300' })
hi(0, "RedrawDebugComposed", { bg = '#005523' })
hi(0, "RedrawDebugNormal", { reverse = true })
hi(0, "RedrawDebugRecompose", { bg = '#590008' })
hi(0, "Removed", { fg = '#d8647e' })
hi(0, "Repeat", { fg = '#6e94b2' })
hi(0, "Search", { fg = '#cdcdcd', bg = '#405065' })
hi(0, "SignColumn", { fg = '#cdcdcd' })
hi(0, "SnippetTabstop", { link = "Visual" })
hi(0, "SnippetTabstopActive", { link = "SnippetTabstop" })
hi(0, "Special", { fg = '#b4d4cf' })
hi(0, "SpecialChar", { fg = '#6e94b2' })
hi(0, "SpecialComment", { fg = '#6e94b2' })
hi(0, "SpecialKey", { fg = '#606079' })
hi(0, "SpellBad", { sp = '#d8647e', undercurl = true })
hi(0, "SpellCap", { sp = '#f3be7c', undercurl = true })
hi(0, "SpellLocal", { sp = '#7e98e8', undercurl = true })
hi(0, "SpellRare", { sp = '#aeaed1', undercurl = true })
hi(0, "Statement", { fg = '#6e94b2' })
hi(0, "StatusLine", { fg = '#cdcdcd', bg = '#1c1c24' })
hi(0, "StatusLineNC", { fg = '#606079' })
hi(0, "StatusLineTerm", { fg = '#cdcdcd', bg = '#1c1c24' })
hi(0, "StatusLineTermNC", { fg = '#606079' })
hi(0, "StderrMsg", { link = "ErrorMsg" })
hi(0, "StorageClass", { fg = '#aeaed1' })
hi(0, "String", { fg = '#e8b589', italic = true })
hi(0, "Structure", { fg = '#aeaed1' })
hi(0, "Substitute", { fg = '#9bb4bc', bg = '#333738' })
hi(0, "TabLine", { bg = '#1c1c24' })
hi(0, "TabLineFill", { link = "TabLine" })
hi(0, "TabLineSel", { fg = '#1c1c24', bg = '#cdcdcd' })
hi(0, "Tag", { fg = '#b4d4cf' })
hi(0, "TermCursor", { reverse = true })
hi(0, "Title", { fg = '#c3c3d5' })
hi(0, "Todo", { fg = '#c48282', italic = true })
hi(0, "Type", { fg = '#9bb4bc' })
hi(0, "Typedef", { fg = '#aeaed1' })
hi(0, "Underlined", { underline = true })
hi(0, "VertSplit", { link = "WinSeparator" })
hi(0, "Visual", { bg = '#333738' })
hi(0, "VisualNOS", { bg = '#606079', underline = true })
hi(0, "WarningMsg", { fg = '#f3be7c', bold = true })
hi(0, "Whitespace", { fg = '#252530' })
hi(0, "WildMenu", { fg = '#141415', bg = '#c48282' })
hi(0, "WinBar", { fg = '#cdcdcd', bg = '#1c1c24' })
hi(0, "WinBarNC", { fg = '#606079' })
hi(0, "WinSeparator", { fg = '#878787' })
hi(0, "debugBreakpoint", { fg = '#141415', bg = '#90a0b5' })
hi(0, "debugPC", { fg = '#141415', bg = '#cdcdcd' })
hi(0, "htmlArg", { fg = '#aeaed1' })
hi(0, "htmlEndTag", { fg = '#cdcdcd' })
hi(0, "htmlSpecialTagName", { fg = '#b4d4cf' })
hi(0, "htmlTag", { fg = '#cdcdcd' })
hi(0, "htmlTagName", { fg = '#b4d4cf' })
hi(0, "lCursor", { fg = '#141415', bg = '#cdcdcd' })
hi(0, "netrwClassify", { fg = '#7e98e8' })
hi(0, "netrwTreeBar", { fg = '#606079' })
hi(0, "qfError", { fg = '#d8647e' })
vim.g.terminal_color_0 = "#252530"
vim.g.terminal_color_1 = "#d8647e"
vim.g.terminal_color_2 = "#7fa563"
vim.g.terminal_color_3 = "#f3be7c"
vim.g.terminal_color_4 = "#6e94b2"
vim.g.terminal_color_5 = "#bb9dbd"
vim.g.terminal_color_6 = "#aeaed1"
vim.g.terminal_color_7 = "#cdcdcd"
vim.g.terminal_color_8 = "#606079"
vim.g.terminal_color_9 = "#e08398"
vim.g.terminal_color_10 = "#99b782"
vim.g.terminal_color_11 = "#f5cb96"
vim.g.terminal_color_12 = "#8ba9c1"
vim.g.terminal_color_13 = "#c9b1ca"
vim.g.terminal_color_14 = "#bebeda"
vim.g.terminal_color_15 = "#d7d7d7"
